# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulation of a neutral network assembly procesess
#'
#' This model simulates an assembly process starting from basal species, that could be fixed with the 
#'   parameter BB or allowed to migrate with rate m. The interactions are established with probability q with 
#'   no restrictions, execpt that double interactions A->B, B->A and self interactions are not allowed. The model 
#'   simulates secondary extinctions, when a predator has all his preys extinct it will become locally exctinct.
#' 
#' @param rho metacommunity number of species
#' @param m   migration rate (probability) from the meta-web   
#' @param q   probability of interaction 
#' @param a   probability of extinction    
#' @param time   time of simulation   
#' @param BB  number of initial basal species present 
#'
#' @return
#'
#' @export
neutralNetAssembly <- function(rho, m, q, a, time, BB = 0L) {
    .Call(`_MetaWebAssemblyModels_neutralNetAssembly`, rho, m, q, a, time, BB)
}

#' Simulation of a Cascade fod web assembly procesess
#'
#' This model simulates an assembly process starting from basal species, that could be fixed with the 
#'   parameter BB or allowed to migrate with rate m. The interactions are established with probability q 
#'   if species i>j then i becomes predator and j prey  (i<--j). The model simulates secondary extinctions, 
#'   when a predator has all his preys extinct it will become locally exctinct.
#' 
#' @param rho    metacommunity number of species
#' @param m      migration rate (probability) from the meta-web   
#' @param q      probability of interaction 
#' @param a      extinctions of species (not proportional to C)   
#' @param time   time of simulation   
#' @param BB     number of basal species if 0 will be ~poison(rho*m)   
#' @return       A list with the final the number of species by time S, the number of links by time L, the number of basal species
#'               and the adjacency matrix A. 
#' @export
cascadeNetAssembly <- function(rho, m, q, a, time, BB = 0L) {
    .Call(`_MetaWebAssemblyModels_cascadeNetAssembly`, rho, m, q, a, time, BB)
}

#' Simulation of an Assembly process from a Meta-web assuming the interactions conserve in the local web 
#'
#' This is a dynamical model of colonization and extinction process, with the restriction 
#' that predators must have at least one prey species to survive in the local community,  described in [1]
#' 
#' @references
#' 
#' 1. Galiana, N., Lurgi, M., Claramunt-López, B., Fortin, M.-J., Leroux, S., Cazelles, K., et al. (2018). 
#' The spatial scaling of species interaction networks. Nat. Ecol. Evol., 2, 782–790
#'
#' @param metaW  metacommunity adyacency matrix 
#' @param m      A numeric vector of species' migration rates (probability) from the meta-web   
#' @param e      A numeric vector of species' extinction probability 
#' @param time   Number of time steps of simulation
#' @return       A list with the final the number of species by time S, the number of links by time L, 
#'               the time series of species STime and the adjacency matrix A with effective links. 
metaWebNetAssembly <- function(metaW, m, e, time) {
    .Call(`_MetaWebAssemblyModels_metaWebNetAssembly`, metaW, m, e, time)
}

#' Simulation of an Assembly process from a Meta-web assuming stochastic Generalized Lotka-Volterra
#' Local dynamics  
#'
#' @param metaW  NumericMatrix, metacommunity interaction matrix, the values and the signs are the parameters of the LV model  
#' @param m      NumericVector, migration rate (probability) from the meta-web   
#' @param r      NumericVector, grow rate of species, could be negative
#' @param ini    NumericVector, initial condition, or 0  
#' @param time   Number of time steps of simulation
#' @param tau    Number of integration steps for Tau leap method 
#' @return       A list with a vector S the final the number of species by time, L the number of links by time, 
#'               STime a time series of each species with dimension nrow(metaW) x time,
#'               and the adjacency matrix A. 
#' @export
metaWebNetAssemblyGLV <- function(metaW, m, r, ini, time, tau = 0.01) {
    .Call(`_MetaWebAssemblyModels_metaWebNetAssemblyGLV`, metaW, m, r, ini, time, tau)
}

#' Calculate the proportion of interacions types in a Lotka-Volterra adjacency matrix
#'
#' @param adjM       Numeric Matrix Lotka-Volterra adjcency matrix  
#' @param sp         Numeric vector with the present species, if species=0 the interaction is not counted
#' 
#' @return           Numeric vector with 5 elements Matrix 1=Mutualistic (+,+), 2=Predator-prey (-,+), 3=Competitive (-,-)
#'                   4=Comensalism (+,0), 5=Amensalism (-,0)
#' @export
calcPropInteractionsGLVadjMat <- function(adjM, spc) {
    .Call(`_MetaWebAssemblyModels_calcPropInteractionsGLVadjMat`, adjM, spc)
}

#' Generate random parameters for Lotka-Volterra generalized interaction matrix from Lotka-Volterra adjacency matrix  
#'
#' @param adjM       NumericMatrix, metacommunity interaction matrix, the values and the signs are 
#'                   the parameters of the LV model then a predator prey interaction will be adjM(i,j)=-1 
#'                   adjM(j,i)=1 where j is the predator and i the prey. Competitive interaction is adjM(i,j)=adjM(j,i)=-1
#' @param ef         Eficiency of predator prey interactions
#' @param predIntMax Maximum value for the interaction intensity of predator-preys, competition, mutalistic. 
#' @param selfLimMax Numeric vector, and  also set the maximum value for diagonal entries of the interaction matrix
#'                   that represent self-limitation, the elements of the vector represent 1=mutualistic, 2=Basal, 3=predator species.
#' @param migrMin    the minimum value to use as interval to generate at uniform random m from migrMin to 1
#' @param preserveInt if true the values of the interactions adjM[i,i] when i!=j are preserved, the minimum value to use as interval to generate at uniform random m from migrMin to 1
#'                    
#' @return           A list with the interaction matrix interM, the intrinsic growth rates r, and migration values m
#' @export
generateGLVparmsFromAdj <- function(adjM, ef, predIntMax = 0.01, selfLimMax = as.numeric( c(0.01, 0.01, 0.01)), migrMin = 0.0, preserveInt = FALSE) {
    .Call(`_MetaWebAssemblyModels_generateGLVparmsFromAdj`, adjM, ef, predIntMax, selfLimMax, migrMin, preserveInt)
}

#' Generate random Lotka-Volterra adjacency matrix with fixed proportion of interactions   
#'
#' @param numSp      Integer, number of species 
#' @param C          Double, Probability of interaction = Connectivity = number of interacions/(numSp^2)
#' @param propInt    Numeric vector, Proportion of interactions, there are 5 types of interactions the elements of the vector
#'                   represent 1= mutualism (+,+), 2=Predator-prey (+,-), 3= competition (-,-), 4=Comensalims (+,0), 
#'                   5=Amensalism (-,0). 
#' @return           A NumericMatrix with the GLV type of adjacency matrix  
#' @export
generateRandomGLVadjMat <- function(numSp, C, propInt) {
    .Call(`_MetaWebAssemblyModels_generateRandomGLVadjMat`, numSp, C, propInt)
}

